version: '3.9'

services:
  php:
    build:
      context: php_service
      dockerfile: Dockerfile
    ports:
      - 6969:80
    volumes:
      - ./src:/var/www/html/

  db:
    build:
      context: db_service
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}